pipeline:
  build_app:
    image: docker:18.03.1-ce
    environment:
      - DOCKER_HOST=tcp://172.17.0.1:2375
    commands:
      - docker build -t icasework-resolver .
    when:
      event: pull_request

  build_app:
    image: docker:18.03.1-ce
    environment:
      - DOCKER_HOST=tcp://172.17.0.1:2375
    commands:
      - docker build -t icasework-resolver-${DRONE_COMMIT_SHA} .
    when:
      branch: master
      event: push

  image_to_quay:
    image: docker:18.03.1-ce
    secrets:
      - DOCKER_PASSWORD
    environment:
      - DOCKER_HOST=tcp://172.17.0.1:2375
    commands:
      - docker login -u="ukhomeofficedigital+icasework_resolver" -p=$${DOCKER_PASSWORD} quay.io
      - docker tag file-vault-$${DRONE_COMMIT_SHA} quay.io/ukhomeofficedigital/icasework-resolver:$${DRONE_COMMIT_SHA}
      - docker push quay.io/ukhomeofficedigital/icasework-resolver:$${DRONE_COMMIT_SHA}
    when:
      branch: master
      event: push
