---
kind: pipeline
name: matrix-1
type: kubernetes

steps:
- name: build_app
  pull: if-not-exists
  image: docker
  commands:
  - docker build -t icasework-resolver .
  when:
    branch: [ master, features/* ]
    event: [ pull_request, push ]

- name: docker-build-and-push
  pull: if-not-exists
  image: ukhomeoffice/drone-docker
  environment:
    DOCKER_PASSWORD:
      from_secret: docker_password
  settings:
    registry: quay.io
    repo: quay.io/ukhomeofficedigital/icasework-resolver
    tags:
    - 2.0.0-${DRONE_BUILD_NUMBER}-${DRONE_COMMIT:0:10}
    - 2.0.0
    - 2
    - 2
    - latest
    username: ukhomeofficedigital+icasework_resolver
  when:
    branch: master
    event: push

...
